# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flickr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'SwiftLint'

  target 'flickrTests' do
    inherit! :search_paths
    use_frameworks!
    pod 'Nimble'
    pod 'Quick'
    
  end

  target 'flickrUITests' do
    # Pods for testing
  end

end
